start complete
Initiating game:  PandaReach-v3
Experiments starting for:  3
Task Name:  CustomReachEnv0
Traceback (most recent call last):
  File "/home/user/Thesis/GUI/gui.py", line 230, in setLblText
    if self.runTrial.trial.agent.trial_timer >= 180:
AttributeError: 'Agent' object has no attribute 'trial_timer'
Traceback (most recent call last):
  File "/home/user/Thesis/GUI/gui.py", line 230, in setLblText
    if self.runTrial.trial.agent.trial_timer >= 180:
AttributeError: 'Agent' object has no attribute 'trial_timer'
done
{'upload': {'projectId': None, 'participantID': '3', 'file': 'trial_3', 'path': './Trials/trial_3'}}
[Errno 2] No such file or directory: './userdata/PandaReach-v3/3/PandaReach-v3_PStable.csv'
Creating new file
[Errno 2] No such file or directory: './userdata/PandaReach-v3/3/PandaReach-v3_Qtable.csv'
Creating new file
start complete
Initiating game:  PandaReach-v3
Experiments starting for:  3
Task Name:  CustomReachEnv0
done
{'upload': {'projectId': None, 'participantID': '3', 'file': 'trial_3', 'path': './Trials/trial_3'}}
[Errno 2] No such file or directory: './userdata/PandaReach-v3/3/PandaReach-v3_PStable.csv'
Creating new file
[Errno 2] No such file or directory: './userdata/PandaReach-v3/3/PandaReach-v3_Qtable.csv'
Creating new file
start complete
Initiating game:  PandaReach-v3
Experiments starting for:  3
Task Name:  CustomReachEnv1
done
{'upload': {'projectId': None, 'participantID': '3', 'file': 'trial_3', 'path': './Trials/trial_3'}}
[Errno 2] No such file or directory: './userdata/PandaReach-v3/3/PandaReach-v3_PStable.csv'
Creating new file
[Errno 2] No such file or directory: './userdata/PandaReach-v3/3/PandaReach-v3_Qtable.csv'
Creating new file
start complete
Initiating game:  PandaReach-v3
Experiments starting for:  3
Task Name:  CustomReachEnv2
done
{'upload': {'projectId': None, 'participantID': '3', 'file': 'trial_3', 'path': './Trials/trial_3'}}
[Errno 2] No such file or directory: './userdata/PandaReach-v3/3/PandaReach-v3_PStable.csv'
Creating new file
[Errno 2] No such file or directory: './userdata/PandaReach-v3/3/PandaReach-v3_Qtable.csv'
Creating new file
start complete
Initiating game:  PandaReach-v3
Experiments starting for:  3
Task Name:  CustomReachEnv3
done
{'upload': {'projectId': None, 'participantID': '3', 'file': 'trial_3', 'path': './Trials/trial_3'}}
User directory created:  /home/user/Thesis/userdata/PandaReach-v3/4
[Errno 2] No such file or directory: './userdata/PandaReach-v3/4/PandaReach-v3_PStable.csv'
Creating new file
[Errno 2] No such file or directory: './userdata/PandaReach-v3/4/PandaReach-v3_Qtable.csv'
Creating new file
start complete
Initiating game:  PandaReach-v3
Experiments starting for:  4
Task Name:  CustomReachEnv1
done
{'upload': {'projectId': None, 'participantID': '4', 'file': 'trial_4', 'path': './Trials/trial_4'}}
[Errno 2] No such file or directory: './userdata/PandaReach-v3/4/PandaReach-v3_PStable.csv'
Creating new file
[Errno 2] No such file or directory: './userdata/PandaReach-v3/4/PandaReach-v3_Qtable.csv'
Creating new file
start complete
Initiating game:  PandaReach-v3
Experiments starting for:  4
Task Name:  CustomReachEnv2
done
{'upload': {'projectId': None, 'participantID': '4', 'file': 'trial_4', 'path': './Trials/trial_4'}}
[Errno 2] No such file or directory: './userdata/PandaReach-v3/4/PandaReach-v3_PStable.csv'
Creating new file
[Errno 2] No such file or directory: './userdata/PandaReach-v3/4/PandaReach-v3_Qtable.csv'
Creating new file
start complete
Initiating game:  PandaReach-v3
Experiments starting for:  4
Task Name:  CustomReachEnv3
done
{'upload': {'projectId': None, 'participantID': '4', 'file': 'trial_4', 'path': './Trials/trial_4'}}
User directory created:  /home/user/Thesis/userdata/PandaReach-v3/5
[Errno 2] No such file or directory: './userdata/PandaReach-v3/5/PandaReach-v3_PStable.csv'
Creating new file
[Errno 2] No such file or directory: './userdata/PandaReach-v3/5/PandaReach-v3_Qtable.csv'
Creating new file
start complete
Initiating game:  PandaReach-v3
Experiments starting for:  5
Task Name:  CustomReachEnv1
done
{'upload': {'projectId': None, 'participantID': '5', 'file': 'trial_5', 'path': './Trials/trial_5'}}
[Errno 2] No such file or directory: './userdata/PandaReach-v3/5/PandaReach-v3_PStable.csv'
Creating new file
[Errno 2] No such file or directory: './userdata/PandaReach-v3/5/PandaReach-v3_Qtable.csv'
Creating new file
start complete
Initiating game:  PandaReach-v3
Experiments starting for:  5
Task Name:  CustomReachEnv2
done
{'upload': {'projectId': None, 'participantID': '5', 'file': 'trial_5', 'path': './Trials/trial_5'}}
[Errno 2] No such file or directory: './userdata/PandaReach-v3/5/PandaReach-v3_PStable.csv'
Creating new file
[Errno 2] No such file or directory: './userdata/PandaReach-v3/5/PandaReach-v3_Qtable.csv'
Creating new file
start complete
Initiating game:  PandaReach-v3
Experiments starting for:  5
Task Name:  CustomReachEnv2
Traceback (most recent call last):
  File "/home/user/Thesis/trial.py", line 158, in start
    self.run()
  File "/home/user/Thesis/trial.py", line 177, in run
    self.end()
  File "/home/user/Thesis/trial.py", line 212, in end
    self.agent.close()
  File "/home/user/Thesis/agent.py", line 604, in close
    self.env.close()
  File "/home/user/panda-gym/panda_gym/envs/core.py", line 328, in close
    self.sim.close()
  File "/home/user/panda-gym/panda_gym/pybullet.py", line 73, in close
    self.physics_client.disconnect()
pybullet.error: Not connected to physics server.
Traceback (most recent call last):
  File "/home/user/Thesis/trial.py", line 158, in start
    self.run()
  File "/home/user/Thesis/trial.py", line 177, in run
    self.end()
  File "/home/user/Thesis/trial.py", line 212, in end
    self.agent.close()
  File "/home/user/Thesis/agent.py", line 604, in close
    self.env.close()
  File "/home/user/panda-gym/panda_gym/envs/core.py", line 328, in close
    self.sim.close()
  File "/home/user/panda-gym/panda_gym/pybullet.py", line 73, in close
    self.physics_client.disconnect()
pybullet.error: Not connected to physics server.
done
[Errno 2] No such file or directory: './userdata/PandaReach-v3/5/PandaReach-v3_PStable.csv'
Creating new file
[Errno 2] No such file or directory: './userdata/PandaReach-v3/5/PandaReach-v3_Qtable.csv'
Creating new file
start complete
Initiating game:  PandaReach-v3
Experiments starting for:  5
Task Name:  CustomReachEnv3
done
{'upload': {'projectId': None, 'participantID': '5', 'file': 'trial_5', 'path': './Trials/trial_5'}}