start complete
Initiating game:  PandaReach-v3
Experiments starting for:  0
Task Name:  CustomReachEnv1
[0.01464405 0.06455681 0.18082901]
[ 0.01346495 -0.02290356  0.19376823]
[-0.01872384  0.1175319   0.28909883]
[-0.03496754  0.08751751  0.15866848]
[0.02041337 0.12767899 0.02131082]
[-0.12386121 -0.14393448  0.24978595]
[0.08344703 0.11100364 0.2935855 ]
done
Traceback (most recent call last):
  File "/home/user/Thesis/GUI/gui.py", line 230, in setLblText
    if self.runTrial.trial.agent.trial_timer >= 180:
AttributeError: 'Agent' object has no attribute 'trial_timer'
Traceback (most recent call last):
  File "/home/user/Thesis/GUI/gui.py", line 230, in setLblText
    if self.runTrial.trial.agent.trial_timer >= 180:
AttributeError: 'Agent' object has no attribute 'trial_timer'
{'upload': {'projectId': None, 'participantID': '0', 'file': 'trial_0', 'path': './Trials/trial_0'}}
[Errno 2] No such file or directory: './userdata/PandaReach-v3/0/PandaReach-v3_PStable.csv'
Creating new file
[Errno 2] No such file or directory: './userdata/PandaReach-v3/0/PandaReach-v3_Qtable.csv'
Creating new file
start complete
Initiating game:  PandaReach-v3
Experiments starting for:  0
Task Name:  CustomReachEnv2
Traceback (most recent call last):
  File "/home/user/Thesis/GUI/gui.py", line 230, in setLblText
    if self.runTrial.trial.agent.trial_timer >= 180:
AttributeError: 'Agent' object has no attribute 'trial_timer'
Traceback (most recent call last):
  File "/home/user/Thesis/GUI/gui.py", line 230, in setLblText
    if self.runTrial.trial.agent.trial_timer >= 180:
AttributeError: 'Agent' object has no attribute 'trial_timer'
done
{'upload': {'projectId': None, 'participantID': '0', 'file': 'trial_0', 'path': './Trials/trial_0'}}